networks:
  vlad-network:

services:
  nginx-core:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './nginx.conf:/etc/nginx/nginx.conf.template'
      - '/etc/letsencrypt:/etc/letsencrypt'
    container_name: nginx-core
    command:
      - 'envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf'
    environment:
      CATS_APP_BASE_PATH: ${CATS_APP_BASE_PATH:-/cats}
    depends_on:
      - home
      - cats-app
    networks:
      - vlad-network

  home:
    build:
      context: home
    container_name: home
    networks:
      - vlad-network

  cats-app:
    build:
      context: ../cats/app
    container_name: cats-app
    environment:
      BASE_PATH: ${CATS_APP_BASE_PATH:-/cats}
    networks:
      - vlad-network