networks:
  vlad-network:

services:
  nginx-core:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    container_name: nginx-core
    environment:
      CATS_APP_BASE_PATH: ${CATS_APP_BASE_PATH:-/cats}
    depends_on:
      - home
      - cats-app
    networks:
      - vlad-network

  home:
    build:
      context: home
    container_name: home
    networks:
      - vlad-network

  cats-app:
    build:
      context: ../cats/app
      args:
        BASE_PATH: ${CATS_APP_BASE_PATH:-/cats}
    container_name: cats-app
    networks:
      - vlad-network