networks:
  vlad-network:

services:
  nginx-core:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    container_name: nginx-core
    depends_on:
      - cats-app
    networks:
      - vlad-network

  cats-app:
    build:
      context: ../cats/app
    environment:
      APP_PATH: /cats
    container_name: cats-app
    networks:
      - vlad-network